trigger: none
pr: none

parameters:
  - name: studentAlias
    type: string
    default: ''
  - name: labNumber
    type: string
    default: '1'

extends:
  template: pipelines/lab.lifecycle.yml
  parameters:
    action: break
    studentAlias: ${{ parameters.studentAlias }}
    labNumber: ${{ parameters.labNumber }}
