trigger: none
pr: none

variables:
  - group: LabConfiguration

parameters:
  - name: studentAlias
    type: string
    default: ''

extends:
  template: pipelines/lab.lifecycle.yml
  parameters:
    action: destroy
    studentAlias: ${{ parameters.studentAlias }}
