trigger: none
pr: none

variables:
  - group: LabConfiguration

parameters:
  - name: labNumber
    type: string
    default: '1'

extends:
  template: pipelines/lab.lifecycle.yml
  parameters:
    action: break
    labNumber: ${{ parameters.labNumber }}
